--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/Minerware
build-by-default: true
branches:
  - master
projects:
  Minerware:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.1.0
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
        branch: master
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
      - src: IvanCraft623/fakeblocks/fakeblocks
        version: ^0.0.2
      - src: IvanCraft623/languages/languages
        version: ^0.0.1
      - src: LatamPMDevs/FormAPI/libFormAPI
        version: ^2.1.0
      - src: poggit/libasynql/libasynql
        version: 4.1.5
