--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/Minerware
build-by-default: true
branches:
  - master
projects:
  Minerware:
    path: ""
    libs:
      - src: LatamPMDevs/Commando/Commando
        version: ^3.1.1
        branch: pm5
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.2.0
      - src: LatamPMDevs/ConfigUpdater/ConfigUpdater
        version: ^2.0.1
        branch: master
      - src: LatamPMDevs/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
      - src: IvanCraft623/fakeblocks/fakeblocks
        version: ^0.0.3
      - src: IvanCraft623/languages/languages
        version: ^0.0.3
      - src: LatamPMDevs/FormAPI/libFormAPI
        version: ^2.1.1
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
