--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/Minerware
build-by-default: true
branches:
  - master
projects:
  Minerware:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: IvanCraft623/languages/languages
        version: ^0.0.1
      - src: poggit/libasynql/libasynql
        version: ^4.0.0
