name: Minerware
version: 1.0.0-beta2
main: LatamPMDevs\minerware\Minerware
api: "4.4.0"
authors:
  - IvanCraft623
  - JustJ0rd4n
  - TheModDev

permissions:
  minerware.command:
    description: "Minerware main command"
    default: true
  minerware.command.arenas:
    description: "Manage minigame arenas"
    default: op
  minerware.command.credits:
    description: "Show plugin credits"
    default: true
  minerware.command.help:
    description: "Show the list of available commands"
    default: true
  minerware.command.join:
    description: "Join a random arena"
    default: true
  minerware.command.language:
    description: "Change the default language of the plugin"
    default: op
